# Generated by Django 3.2.5 on 2021-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_image', models.CharField(default=None, max_length=500)),
                ('preferences', models.CharField(choices=[('ME', 'Men'), ('WO', 'Women'), ('BI', 'Bisexual')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(default=None)),
                ('interests', models.ManyToManyField(to='interests.Interest')),
            ],
        ),
    ]
